version: "3.8"
services:
  php:
    environment:
      APP_DEBUG: 'true'
      APP_ENV: 'local'
      DEV_FOLDERS: '/var/www/packages'
    volumes:
      - ./packages:/var/www/packages:cached
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seatplus_route.rule=Host(`${COMPOSE_PROJECT_NAME}.test`)"
      - "traefik.http.routers.seatplus_route.service=${COMPOSE_PROJECT_NAME}_service"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_service.loadbalancer.server.port=80"
  cron:
    volumes:
      - ./packages:/var/www/packages:cached
  worker:
    volumes:
      - ./packages:/var/www/packages:cached
  mariadb:
    ports:
      - target: 3306
        published: 3306
        mode: host
  redis:
    ports:
      - target: 6379
        published: 6379
        mode: host
  testdb:
    image: mariadb:10.7
    tmpfs: /var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: testbench
      MARIADB_USER: default
      MARIADB_PASSWORD: secret
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - backend
  node:
    user: "${PUID}:${PGID}"
    volumes:
      - ./packages:/var/www/packages:cached
    ports:
      - "5173:5173"
    command: ["/bin/sh", "-c", "npm install && npm run dev --host"]
