version: "3.8"
services:
  php:
    environment:
      APP_DEBUG: 'true'
      APP_ENV: 'local'
      DEV_FOLDERS: '/var/www/packages'
    volumes:
      - ./packages:/var/www/packages:cached
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seatplus_route.rule=Host(`${COMPOSE_PROJECT_NAME}.test`)"
      - "traefik.http.routers.seatplus_route.service=${COMPOSE_PROJECT_NAME}_service"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_service.loadbalancer.server.port=80"
  mariadb:
    ports:
      - target: 3306
        published: 3306
        mode: host
  testdb:
    image: mariadb:10.7
    tmpfs: /var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=testbench
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
  node:
    command: ["/bin/sh", "-c", "npm install && npm run watch"]
