services:
  php:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.seatplus_route.rule=Host(`seatplus.net`)"
      - "traefik.http.routers.seatplus_route.entrypoints=websecure"
      - "traefik.http.routers.seatplus_route.tls.certresolver=myresolver"
  node:
    command: ["/bin/sh", "-c", "npm install && npm run prod"]
