version: "3.8"

services:

  traefik:
    image: "traefik:v2.9"
    restart: always
    container_name: "traefik"
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
